### ISSUE TITLE
The total cash amount available now should be displayed by denomination

### ISSUE THREAD

**Issue by elvisISS** [preethimrao/Configuration-Management-CA-VCMS#1]
The system only displays the total cash amount now. And the total cash amount available now should be displayed by denomination.

**Comment by preethimrao** [comment]
Issue closed by mistake

**Comment by nwenihan** [comment]
The enhancements have been implemented. @preethimrao kindly test and review it.

**Comment by preethimrao** [comment]
The enhancement is tested and reviewed.
