### ISSUE TITLE
Data not reset after session

### ISSUE THREAD

**Issue by elvisISS** [preethimrao/Configuration-Management-CA-VCMS#2]
The total cash held should be reset after user push the "Press to collect all cash" button.

**Comment by preethimrao** [comment]
The bug is fixed and tested successfully

**Comment by preethimrao** [comment]
Issue was closed by mistake.

**Comment by nwenihan** [comment]
This bug is fixed. @preethimrao Please test and review it

**Comment by preethimrao** [comment]
The bug fix is tested and reviewed
